language: php

php:
  - 7.2.20

services:
  - mariadb

addons:
  mariadb: "10.4"

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --no-interaction --verbose
  - php artisan passport:configure

before_install:
  - mysql -e 'CREATE DATABASE testing;'

script:
  -  ./vendor/bin/phpunit

cache:
  directories:
    - vendor

branches:
  only:
    - master
